package ${packageName};

<#if needsUUID>
import java.util.UUID;
</#if>
<#if needsLocalDateTime>
import java.time.LocalDateTime;
</#if>

/**
 * Domain entity: ${entityName}
 * 
 * Generated by Clean Architecture Generator.
 */
public class ${entityName} {

<#if hasId>
    private ${idType} id;
</#if>
<#list fields as field>
    private ${field.type} ${field.name};
</#list>

    // Constructors

    public ${entityName}() {
    }

    public ${entityName}(<#if hasId>${idType} id<#if fields?size gt 0>, </#if></#if><#list fields as field>${field.type} ${field.name}<#if field?has_next>, </#if></#list>) {
<#if hasId>
        this.id = id;
</#if>
<#list fields as field>
        this.${field.name} = ${field.name};
</#list>
    }

    // Getters and Setters

<#if hasId>
    public ${idType} getId() {
        return id;
    }

    public void setId(${idType} id) {
        this.id = id;
    }

</#if>
<#list fields as field>
    public ${field.type} get${field.name?cap_first}() {
        return ${field.name};
    }

    public void set${field.name?cap_first}(${field.type} ${field.name}) {
        this.${field.name} = ${field.name};
    }

</#list>
    // Business methods

    // TODO: Add business logic methods here

    @Override
    public String toString() {
        return "${entityName}{" +
<#if hasId>
                "id=" + id +
<#if fields?size gt 0>
                ", " +
</#if>
</#if>
<#list fields as field>
                "${field.name}=" + ${field.name}<#if field?has_next> +
                ", " +
</#if>
</#list> +
                '}';
    }
}
