package ${basePackage}.infrastructure.config;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main application class for ${projectName}.
 * 
 * Generated by Clean Architecture Generator.
 */
@SpringBootApplication(scanBasePackages = "${basePackage}")
public class ${projectNamePascalCase}Application {
    
    public static void main(String[] args) {
        SpringApplication.run(${projectNamePascalCase}Application.class, args);
    }
}
